spring:
  application:
    name: service1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IAM_URL}

server:
  port: 8081

IAM_URL: "http://localhost:9090/realms/spring"
